export const areasOfActivity = [
  {
    id: "saude",
    title: "Saúde",
    kicker: "Clínicas e hospitais",
    headline: "Energia contínua para o que é essencial",
    subtitle: "Cuidar de pessoas é a nossa energia.",
    description:
      "Backup para consultas, exames, cirurgias, emergência e terapia intensiva — com atendimento imediato 24h.",
    image: "/areas/saude-hospital.jpg",
    extraImage: "/areas/saude-clinica.jpg",
    features: [
      "Energia contínua para o que é essencial",
      "Suporte técnico 24h com atendimento imediato",
      "Segurança e confiança para sua clínica ou hospital",
      "Cobertura para consultas, exames, cirurgias e UTI",
    ],
    bars: [
      { label: "Atendimento 24 horas" },
      { label: "Equipamentos confiáveis" },
      { label: "Equipe técnica especializada" },
    ],
    slogan: "Segurança e confiança para sua clínica",
  },
  {
    id: "agronegocio",
    title: "Agronegócio",
    kicker: "Campo, silo e produção",
    headline: "Energia para produzir com segurança e eficiência",
    subtitle: "Soluções em energia que garantem continuidade para todas as etapas do agronegócio.",
    description: "Produtividade sem interrupções, equipamentos robustos e suporte técnico especializado no campo.",
    image: "/areas/agronegocio.jpg",
    features: [
      "Produtividade sem interrupções",
      "Mais eficiência para o campo",
      "Equipamentos robustos e confiáveis",
      "Suporte técnico especializado",
    ],
    bars: [
      { label: "Energia contínua para o que é essencial" },
      { label: "Atendimento 24 horas" },
      { label: "Equipe técnica especializada" },
      { label: "Segurança e confiança para o seu negócio" },
    ],
    slogan: "Energia contínua para o que é essencial",
  },
  {
    id: "supermercados",
    title: "Supermercados",
    kicker: "Varejo e câmaras frias",
    headline: "Energia que mantém seu supermercado sempre abastecido!",
    subtitle: "Soluções em energia que garantem continuidade, segurança e qualidade em todos os momentos.",
    description:
      "Proteção para câmaras frias, caixas, sistemas e iluminação — energia que não para, negócio que não para.",
    image: "/areas/supermercado.jpg",
    features: [
      "Continuidade nas operações sem interrupções",
      "Proteção total para câmaras frias e alimentos",
      "Energia confiável para caixas, sistemas e iluminação",
      "Mais segurança e tranquilidade para o seu negócio",
      "Suporte técnico especializado 24 horas",
    ],
    bars: [
      { label: "Energia contínua para o que é essencial" },
      { label: "Atendimento 24 horas todo o Brasil" },
      { label: "Equipamentos modernos e eficientes" },
      { label: "Equipe técnica especializada e qualificada" },
    ],
    slogan: "Energia que não para, negócio que não para!",
  },
  {
    id: "condominios",
    title: "Condomínios",
    kicker: "Verticais e horizontais",
    headline: "Energia que gera tranquilidade",
    subtitle: "Soluções para manter elevadores, portarias, bombas, iluminação e áreas comuns sempre em funcionamento.",
    description: "Equipamentos silenciosos, segurança 24h e atendimento próximo para moradores e síndicos.",
    image: "/areas/condominios.jpg",
    features: [
      "Energia contínua para elevadores, bombas e portarias",
      "Segurança 24h e proteção para o condomínio",
      "Iluminação de emergência para áreas comuns e garagens",
      "Equipamentos silenciosos para o dia a dia",
      "Atendimento 24h com suporte técnico rápido",
    ],
    groups: [
      {
        title: "Condomínios verticais",
        text: "Energia que garante conforto, segurança e tranquilidade nos prédios.",
      },
      {
        title: "Condomínios horizontais",
        text: "Energia para uma vida tranquila e sem interrupções no condomínio fechado.",
      },
    ],
    bars: [
      { label: "Confiança" },
      { label: "Autonomia" },
      { label: "Tecnologia silenciosa" },
      { label: "Atendimento próximo" },
    ],
    slogan: "Energia que gera tranquilidade!",
  },
  {
    id: "eventos",
    title: "Eventos",
    kicker: "Shows, produções e celebrações",
    headline: "Energia que faz seu evento acontecer!",
    subtitle: "Soluções completas em energia para shows, eventos e produções de todos os portes.",
    description:
      "Traga seu evento. A gente leva a energia — com equipamentos potentes, silenciosos e suporte antes, durante e depois.",
    image: "/areas/eventos.jpg",
    features: [
      "Energia contínua sem interrupções para um evento perfeito",
      "Equipamentos potentes e silenciosos com alta performance",
      "Suporte técnico especializado antes, durante e depois do evento",
      "Atendimento 24 horas em todo o Brasil",
    ],
    categories: ["Shows e concertos", "Eventos corporativos", "Festas e celebrações", "Estruturas de médio e grande porte"],
    bars: [
      { label: "Segurança e confiança" },
      { label: "Qualidade que gera resultados" },
      { label: "Equipe pronta para te atender" },
    ],
    slogan: "Traga seu evento. A gente leva a energia!",
  },
  {
    id: "industria",
    title: "Empresas e Indústrias",
    kicker: "Operação contínua",
    headline: "Soluções em energia para empresas e indústrias",
    subtitle: "Energia contínua para manter sua operação sempre em movimento.",
    description:
      "Backup para processos críticos, mais produtividade e equipamentos de alto desempenho com suporte 24h.",
    image: "/areas/industria.jpg",
    features: [
      "Energia contínua para processos críticos",
      "Mais produtividade e eficiência operacional",
      "Equipamentos robustos e de alto desempenho",
      "Suporte técnico especializado 24 horas",
    ],
    bars: [
      { label: "Segurança e confiabilidade para sua empresa" },
      { label: "Atendimento imediato em todo o projeto" },
      { label: "Tecnologia de ponta e alta eficiência" },
      { label: "Equipe especializada e qualificada" },
    ],
    slogan: "Energia que mantém sua indústria sempre ativa!",
  },
];
